name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  SDL_VERSION: 2.0.22

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install freeglut3-dev
    
    - name: Install SDL
      run: |
        git clone -b release-${SDL_VERSION} https://github.com/libsdl-org/SDL
        mkdir -p SDL/build
        pushd SDL/build
        ../configure
        make -j 2
        sudo make install
        popd
        rm -rf SDL

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
