name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  SDL_VERSION: 2.0.22

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up bazel
      run: brew install bazel

    - name: Build
      run: bazel build //shooting-game

    - name: Test
      working-directory: ${{github.workspace}}
      run: bazel test //...

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: shooting-game-${{matrix.os}}
        path: build/shooting-game
